### ISSUE TITLE
Erase button doesn't removes the image

### ISSUE THREAD

**Issue by Mon-Tea** [bwaidelich/Wwwision.Neos.MediaBrowserDialog#3]
If I try to remove an image with the erase button and saving the record, the last image appears in the view.

**Comment by bwaidelich** [comment]
@Mon-Tea Thanks for reporting. But I fail to comprehend or reproduce the issue. E.g. there is no "erase button". There is only `asset-replace` that unsets a previously selected asset from the form.
Can you share some code?

**Comment by bwaidelich** [comment]
@Mon-Tea can you please check whether #4 fixes the issue for you?

To test this, you can simply replace the contents of `Packages/Application/Wwwision.Neos.MediaBrowserDialog/Resources/Public/dist.js` with https://raw.githubusercontent.com/bwaidelich/Wwwision.Neos.MediaBrowserDialog/780fae98e84a1a76ca5206f07b3bc9dc2d55ee1f/Resources/Public/dist.js

**Comment by Mon-Tea** [comment]
Sorry @bwaidelich currently I can't … atm I can't reproduce this myself…
But be right back here, if so.

thanks

**Comment by bwaidelich** [comment]
OK, thanks for getting back.

I'll close this for now, but feel free to comment/reopen if you still observe the issue.
